################################
################################
##                            ##
##   OPTION: server           ##
##                            ##
##   Values:                  ##
##   - default (auto-load)    ##
##   - select (select maps)   ##
##   - tourney (tournament)   ##
##                            ##
################################
################################

################################
################################
##                            ##
##   OPTION: name             ##
##                            ##
##   Supply the name of the   ##
##   Server                   ##
##   Defaults to 'default'    ##
##                            ##
################################
################################

################################
################################
##                            ##
##   OPTION: maps             ##
##   This is only needed      ##
##   if the server value      ##
##   is set to 'select'       ##
##                            ##
##   Input maps like so:      ##
##   maps:                    ##
##     '[name]':              ##
##       short: '[short]      ##
##       src: '[src-folder]   ##
##                            ##
################################
################################

################################
################################
##                            ##
##   OPTION: settings         ##
##   This is only needed      ##
##   if the server value      ##
##   is set to 'select'       ##
##                            ##
##   Input maps like so:      ##
##   maps:                    ##
##     '[name]':              ##
##       short: '[short]      ##
##       src: '[src-folder]   ##
##                            ##
################################
################################

server: default
name: default
maps: {}

repo:
  maps: maps/
  libs: libs/
  rotations: rotations.xml